export const projects = [
  {
    title: "TrackTrekker",
    imgname: "tracktrekker",
    description: "Song suggester",
    technologies: "react · typescript · spotify api · cypress",
    link: "https://alux444.github.io/tracktrekker/",
    github: "https://github.com/alux444/tracktrekker",
  },
  {
    title: "Rat Dungeon",
    imgname: "ratdungeon",
    description: "Rogue-like game",
    technologies: "python · tcod",
    github: "https://github.com/alux444/roguelike-game",
  },
  {
    title: "KiwiMart",
    imgname: "kiwimart",
    description: "E-commerce site",
    technologies: "react · firebase · tailwind",
    link: "https://alux444.github.io/online-store/",
    github: "https://github.com/alux444/online-store",
  },
  {
    title: "Chat App",
    imgname: "chatapp",
    description: "Real-time chatapp",
    technologies: "react · firebase · github actions",
    link: "https://alux444.github.io/firebase-chatapp/",
    github: "https://github.com/alux444/firebase-chatapp",
  },
  {
    title: "Weather App v2",
    imgname: "weatherapp",
    description: "Revisited weather app",
    technologies: "react · weatherapi.com · materialsui",
    link: "https://alux444.github.io/weather-remastered/",
    github: "https://github.com/alux444/weather-remastered",
  },
  {
    title: "Project Fitness",
    imgname: "projectfitness",
    description: "Exercise suggester",
    technologies: "react · exercisedb api · youtubesearch api",
    link: "https://alux444.github.io/project-fitness/",
    github: "https://github.com/alux444/project-fitness",
  },
];
