export const projects = [
  {
    title: "TrackTrekker",
    imgname: "tracktrekker",
    description: "Song suggester",
    technologies: "React · Typescript · Spotify API · Cypress",
    link: "https://alux444.github.io/tracktrekker/",
    github: "https://github.com/alux444/tracktrekker",
  },
  {
    title: "Rat Dungeon",
    imgname: "ratdungeon",
    description: "Rogue-like game",
    technologies: "Python · tcod",
    github: "https://github.com/alux444/roguelike-game",
  },
  {
    title: "KiwiMart",
    imgname: "kiwimart",
    description: "E-commerce site",
    technologies: "React · Firebase · Tailwind",
    link: "https://alux444.github.io/online-store/",
    github: "https://github.com/alux444/online-store",
  },
  {
    title: "Chat App",
    imgname: "chatapp",
    description: "Real-time chatapp",
    technologies: "React · Firebase · GitHub Actions",
    link: "https://alux444.github.io/firebase-chatapp/",
    github: "https://github.com/alux444/firebase-chatapp",
  },
  {
    title: "Weather App v2",
    imgname: "weatherapp",
    description: "Revisited weather app",
    technologies: "React · Weatherapi.com · MaterialsUI",
    link: "https://alux444.github.io/weather-remastered/",
    github: "https://github.com/alux444/weather-remastered",
  },
  {
    title: "Project Fitness",
    imgname: "projectfitness",
    description: "Exercise suggester",
    technologies: "React · ExerciseDB API · YoutubeSearch API",
    link: "https://alux444.github.io/project-fitness/",
    github: "https://github.com/alux444/project-fitness",
  },
];
